version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Debug SSH Key
          command: cat /tmp/CA-KEY.pem
      - run:
          name: Deploy to EC2
          command: |
            echo "$SSH_KEY" > /tmp/CA-KEY.pem
            chmod 600 /tmp/CA-KEY.pem  # Ensure it's private

            cat /tmp/CA-KEY.pem

            ssh -o StrictHostKeyChecking=no -i /tmp/CA-KEY.pem ubuntu@23.23.227.94 "
              cd /home/ubuntu/my-app && 
              git pull && 
              sudo systemctl restart gunicorn
            "

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
