version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build

jobs:
  build:
    working_directory: ~/Simple_Application
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@5
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-app-web
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USER@$AWS_EC2_PUBLIC_DNS "
            export SERVER='${SERVER}';
            export PRIVATE_KEY='${PRIVATE_KEY}';
            rm -rf DevOpsCa || true;
            git clone https://github.com/janekeyes/DevOpsCa.git;
            cd DevOpsCa/SimpleApplication/;
            chmod +x deploy.sh && ./deploy.sh"
